### ISSUE TITLE
Show number of days since latest release

### ISSUE THREAD

**Issue by ryanmoran** [paketo-buildpacks/dashboard#9]
## What happened?

* What were you attempting to do?
When I visit the repo list page, I wanted to know how many days had passed since the latest release of a specific buildpack.

* What did you expect to happen?
I expected to see an indication of the time since the latest release.

## Checklist

* [x] I have included steps for reproduction.

**Comment by phil9909** [comment]
@ryanmoran I started working on this. I have the necessary data now, but wonder how to display it. There is not much room, maybe as a tooltip when hovering over the version? WDYT?


Currently it looks like this:

![image](https://user-images.githubusercontent.com/24714828/197184516-17136624-0e24-4129-88fe-34d3566790be.png)


See this branch: https://github.com/sap-contributions/dashboard/tree/9-time-since-last-release

**Comment by fg-j** [comment]
As a maintainer, a tooltip when hovering over the version sounds great 😄

**Comment by ryanmoran** [comment]
I really appreciate that you are helping us with this. The dashboard has been something I've not been able to find time to work on for a while and so I'm really happy to see it getting some love. I would go with the tooltip direction to keep from cluttering the existing tile. I need to rethink the design of the tile anyway as its already kind of broken with the additions of these repos with long names like `builder-jammy-buildpackless-base`.

**Comment by phil9909** [comment]
I switched it to use a tooltip and opened PR https://github.com/paketo-buildpacks/dashboard/pull/153

> I need to rethink the design of the tile anyway as its already kind of broken with the additions of these repos with long names like `builder-jammy-buildpackless-base`.

Yeah, I thought the same when I saw this. Maybe a table would be better.
